[package]
name = "cejn"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
biodivine-lib-bdd = "0.5.13"
biodivine-lib-param-bn = "0.5.10"
