name: performance-regression-test

# This should ensure that the workflow won't run on `dev-*` branches but will
# otherwise execute on any other branch and any pull request (including from
# `dev-*` branches).

on:
  push:
    branches-ignore:
      - 'dev-*'
  pull_request:
    branches:
      - '*'

env:
  # A fixed version used for testing so that the builds don't
  # spontaneously break after a few years.
  # Make sure to update this from time to time.
  RUST_VERSION: "1.86.0"

jobs:


  # Run a basic code validity check, just to make sure
  # everything is ok.
  check:
    name: Check
    runs-on: self-hosted    
    env:
      RUSTFLAGS: "-D warnings"
    steps:
      - uses: actions/checkout@v4      
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUST_VERSION }}
      - run: cargo check

  # This is just an example, we probably want 
  # to run a bunch of models within one test.
  run-chain-saturation:
    name: Run chain saturation
    needs: check
    runs-on: self-hosted
    env:
      RUSTFLAGS: "-D warnings"
    steps:
      - uses: actions/checkout@v4      
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUST_VERSION }}
      - run: cargo build --release
      - run: (time ./target/release/chain_saturation ./models/bbm-inputs-true/026.aeon) &> 026.result.txt
      # Upload test results as artifacts of this CI run:
      - uses: actions/upload-artifact@v4
        with:
          name: run-chain-result
          path: '*.result.txt'
